import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/themecontext";

export const metadata: Metadata = {
  title: "Promise's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {


  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
